### PR TITLE
Add missing Make dependencies

### PR DESCRIPTION
**Pull request by StefanosChaliasos**
Hello

This pull request fixes the build script of this project.
Specifically, it adds missing Make dependencies so that the targets of the project are re-generated correctly whenever there are updates to any of the dependent source files.

In this way, the project is incrementally built and we no longer sacrifice time in clean builds (i.e., builds after a make clean).

Note that this fix follows the best practices for tracking dependencies automatically (through gcc -MD)

For more details, see here.
https://www.gnu.org/software/make/manual/html_node/Automatic-Prerequisites.html

### CODE REVIEW

**Comment by gvoirin** [comment]
Hello Stefanos and thanks a lot for your input! I'd like to push your work to the master branch however a few Travis CI builds are now failing during the linking process, could you check this out?

**Comment by StefanosChaliasos** [comment]
Unfortunately, I couldn't reproduce the error. Are you sure that this commit produced this error?

**Comment by gvoirin** [comment]
Well, technically, yes: if you look here: https://travis-ci.org/centaurean/density/builds/633302636, build 268 has 3 errors whereas build 267 (https://travis-ci.org/centaurean/density/builds/364559242) has none.
This is only for some very specific compiler/platform pairs which might not be too much of a concern overall - it could also be due to a change of software at Travis as well, as build 267 is dated now - but if you had had an idea of what could have caused the problem that would have been somewhat interesting.
If we are reasonably convinced that this is due to Travis itself and not the new makefiles, could you comment out in the .travis.yml file the 3 problematic platform/compiler pairs so that your pull request passes all checks?
Thanks a lot !

**Comment by StefanosChaliasos** [comment]
I commented out the problematic pairs.

**Comment by gvoirin** [comment]
Thank you !

**Pull request merged**
